// Code generated by "stringer -type=State"; DO NOT EDIT

package work

import "fmt"

const _State_name = "UnknownStateNotStartedAdminNotStartedRunningPausingPausedAdminPausedCrisisPausedCompletedFailedStoppingStopped"

var _State_index = [...]uint8{0, 12, 22, 37, 44, 51, 57, 68, 80, 89, 95, 103, 110}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return fmt.Sprintf("State(%d)", i)
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
